#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f clktick.vcd

#run verilator to translate verilog into c++, including c++ testbench
verilator -Wall --cc --trace toplayer.sv --exe toplayer_tb.cpp

#build c++ project via make automatically generated by verilator
make -j -C obj_dir/ -f Vtoplayer.mk Vtoplayer

#run executable simulation file
obj_dir/Vtoplayer
