#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f waveform.vcd

#run verilator to translate verilog into c++, including c++ testbench
verilator -Wall --cc --trace f1_fsm.sv --exe f1_fsm_tb.cpp

#build c++ project via make automatically generated by verilator
make -j -C obj_dir/ -f Vf1_fsm.mk Vf1_fsm

#run executable simulation file
obj_dir/Vf1_fsm
